Document: w1-rrd
Title: Debian w1-rrd Manual
Author: <insert document author here>
Abstract: This manual describes what w1-rrd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/w1-rrd/w1-rrd.sgml.gz

Format: postscript
Files: /usr/share/doc/w1-rrd/w1-rrd.ps.gz

Format: text
Files: /usr/share/doc/w1-rrd/w1-rrd.text.gz

Format: HTML
Index: /usr/share/doc/w1-rrd/html/index.html
Files: /usr/share/doc/w1-rrd/html/*.html
